# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20170519_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatprofile',
            name='hardworking',
            field=models.CharField(choices=[("Don't care", "Don't care"), ('Absolutely', 'Absolutely'), ('A bit', 'A bit'), ('Not really', 'Not really'), ('Absolutely not', 'Absolutely not')], default="Don't care", max_length=20),
        ),
        migrations.AlterField(
            model_name='flatprofile',
            name='partying',
            field=models.CharField(choices=[("Don't care", "Don't care"), ('Absolutely', 'Absolutely'), ('A bit', 'A bit'), ('Not really', 'Not really'), ('Absolutely not', 'Absolutely not')], default="Don't care", max_length=20),
        ),
        migrations.AlterField(
            model_name='flatprofile',
            name='traveling',
            field=models.CharField(choices=[("Don't care", "Don't care"), ('Absolutely', 'Absolutely'), ('A bit', 'A bit'), ('Not really', 'Not really'), ('Absolutely not', 'Absolutely not')], default="Don't care", max_length=20),
        ),
    ]
