# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
